spring:
  application:
    name: api-gateway-Đại
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Request-Id, ${random.uuid}
      httpclient:
        connect-timeout: 5000
        response-timeout: 8s

server:
  port: 8000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
