spring:
  application:
    name: notification-analytics-service-SÆ¡n
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:29092}
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:notification_db}
    username: notificationuser
    password: notificationpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
server:
  port: 8005

logging:
  level:
    root: INFO
    com.eventticket: DEBUG
