spring:
  application:
    name: ticketing-service-Phong
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:ticketing_db}
    username: ticketinguser
    password: ticketingpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:29092}
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      max-poll-records: 10
    listener:
      poll-timeout: 3000
      type: batch
      ack-mode: manual

server:
  port: 8004

logging:
  level:
    "[org.springframework.web]": INFO
    "[org.hibernate]": WARN
